let Pseudo="shadowX";
let Niveau=12;
let Age =21;
let Score=4580;
let Pays= "Maroc";
console.log("Pseudo :" + Pseudo);
console.log("Niveau :" + Niveau);
console.log("Age :" + Age);
console.log("Score :" + Score);
console.log("Pays :" + Pays);
